vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block_private = "10.0.2.0/24"
subnet_cidr_block_public = "10.0.1.0/24"
avail_zone = "us-west-1a"
env_prefix = "test"
instance_type = "t2.micro"
public_key_location = "/home/sha/.ssh/id_rsa.pub"
private_key_location = "/home/sha/.ssh/id_rsa"